<?php 
	$ocupaciones = [
		"ABOGADO", 
		"ACTOR/ARTISTA/MODELO/MÚSICO/DIRECTOR DE ARTE",
		"ADMINISTRADOR",
		"ADUANERO/AGENTE DE ADUANAS/INSPECTOR",
		"AEROMOZO/AZAFATA",
		"AGENTE INMOBILIARIO",
		"AGENTE DE BOLSA",
		"AGENTE DE INMIGRACIÓN/MIGRACIÓN",
		"AGENTE DE TURISMO/VIAJES",
		"AGENTE/CORREDOR DE SEGUROS",
		"AGRICULTOR/AGRÓNOMO/TOPÓGRAFO",
		"ALBAÑIL/OBRERO DE CONSTRUCCIÓN",
		"AMA DE CASA",
		"DESEMPLEADO",
		"EMPRESARIO",
		"ESTUDIANTE",
		"JUBILADO",
		"TRABAJADOR DEPENDIENTE",
		"TRABAJADOR INDEPENDIENTE",
		"OTROS"
		];
?>
