<?php
	$situacionLaboral = [
		"AMA DE CASA", 
		"DESEMPLEADO", 
		"EMPLEADO FORMAL", 
		"EMPLEADOR",
		"ESTUDIANTE",
		"JUBILADO",
		"TRABAJADOR DEPENDIENTE",
		"TRABAJADOR INDEPENDIENTE",
		"TRABAJADOR INFORMAL",
		"OTROS"
		];
?>
